-- MySQL Script generated by MySQL Workbench
-- Sun Feb 18 21:36:20 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mi_libreria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mi_libreria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mi_libreria` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `mi_libreria` ;

-- -----------------------------------------------------
-- Table `mi_libreria`.`author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi_libreria`.`author` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `author` VARCHAR(100) NOT NULL,
  `birth` DATE NULL DEFAULT NULL,
  `nationality` VARCHAR(100) NULL DEFAULT NULL,
  `mother_tongue` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mi_libreria`.`editorial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi_libreria`.`editorial` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `editorial` VARCHAR(100) NOT NULL,
  `formato` VARCHAR(50) NULL DEFAULT 'Fisico',
  `Foundation` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mi_libreria`.`book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi_libreria`.`book` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name_author_id` INT NULL DEFAULT NULL,
  `page` INT NULL DEFAULT NULL,
  `editorial_id` INT NULL DEFAULT NULL,
  `publication` VARCHAR(100) NULL DEFAULT NULL,
  `name_book` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_book_author`
    FOREIGN KEY (`name_author_id`)
    REFERENCES `mi_libreria`.`author` (`id`),
  CONSTRAINT `fk_book_editorial`
    FOREIGN KEY (`editorial_id`)
    REFERENCES `mi_libreria`.`editorial` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_book_author` ON `mi_libreria`.`book` (`name_author_id` ASC) VISIBLE;

CREATE INDEX `fk_book_editorial` ON `mi_libreria`.`book` (`editorial_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mi_libreria`.`gender`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi_libreria`.`gender` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `gender` VARCHAR(50) NOT NULL,
  `depcription` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mi_libreria`.`book_gender`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi_libreria`.`book_gender` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `book_id` INT NULL DEFAULT NULL,
  `gender_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `book_id_book_gender`
    FOREIGN KEY (`book_id`)
    REFERENCES `mi_libreria`.`book` (`id`),
  CONSTRAINT `gender_id_book_gender`
    FOREIGN KEY (`gender_id`)
    REFERENCES `mi_libreria`.`gender` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 38
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `book_id_book_gender` ON `mi_libreria`.`book_gender` (`book_id` ASC) VISIBLE;

CREATE INDEX `gender_id_book_gender` ON `mi_libreria`.`book_gender` (`gender_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mi_libreria`.`interest_book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi_libreria`.`interest_book` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_book` INT NOT NULL,
  `remark` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_interest_book`
    FOREIGN KEY (`id_book`)
    REFERENCES `mi_libreria`.`book` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_interest_book` ON `mi_libreria`.`interest_book` (`id_book` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mi_libreria`.`pending_book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi_libreria`.`pending_book` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_book` INT NOT NULL,
  `purchase_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_pending_book`
    FOREIGN KEY (`id_book`)
    REFERENCES `mi_libreria`.`book` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_pending_book` ON `mi_libreria`.`pending_book` (`id_book` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mi_libreria`.`ranking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi_libreria`.`ranking` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ranking` VARCHAR(40) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mi_libreria`.`read_book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi_libreria`.`read_book` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_book` INT NOT NULL,
  `start_read` DATE NULL DEFAULT NULL,
  `finish_read` DATE NULL DEFAULT NULL,
  `id_ranking` INT NOT NULL,
  `opinion` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_interest_ranking`
    FOREIGN KEY (`id_ranking`)
    REFERENCES `mi_libreria`.`ranking` (`id`),
  CONSTRAINT `fk_read_book`
    FOREIGN KEY (`id_book`)
    REFERENCES `mi_libreria`.`book` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_read_book` ON `mi_libreria`.`read_book` (`id_book` ASC) VISIBLE;

CREATE INDEX `fk_interest_ranking` ON `mi_libreria`.`read_book` (`id_ranking` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

use mi_libreria;
show tables;


